CREATE TABLE IF NOT EXISTS telephones (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    fname TEXT NOT NULL DEFAULT '',
    phone VARCHAR(11) NOT NULL DEFAULT '',
    bank TEXT NOT NULL DEFAULT '',
    checked TINYINT(1) DEFAULT 0
)